[package]
name = "relcat"
version = "0.1.0"
edition = "2021"
authors = ["Eric Keranen <eric@erickeranen.com>"]

[dependencies]
chrono = "0.4"
clap = { version = "3.1.2", features = ["derive"] }
logcat = { path = "../logcat" }
